/**
 * Defines a set of {@link org.estatio.app.services.exceprecog.ExceptionRecognizersForEstatio exception recognizers} that
 * customise any error messages generated by the system into a user-friendly message.
 * 
 *  <p>
 *  The messages that are recognized and are converted are typically database error messages, with constraint errors 
 *  such as unique index violations.  These are converted into messages such as &quot;reference already in use&quot;. 
 */
package org.estatio.app.services.exceprecog;