= incode-module-communications
:_imagesdir: ./


This module currently depends on the original Estatio implementation of commchannel (too much to attempt to also migrate to the existing incode-module-commchannel in one go).


== Domain Model

The following class diagram highlights the main concepts:


[plantuml,images/class-diagram,png]
--
skinparam class {
	BackgroundColor<<PPT>> LightGreen
	BackgroundColor<<Party>> LightGreen
	BackgroundColor<<Place>> LightGreen
	BackgroundColor<<Thing>> LightGreen
	BackgroundColor<<Role>> Khaki
	BackgroundColor<<Desc>> LightSkyBlue
	BackgroundColor<<MI>> LightPink
	BackgroundColor<<MomentOfTime>> LightPink
	BackgroundColor<<IntervalOfTime>> LightPink
	ArrowColor Black
	BorderColor Black
}

hide members
show Paperclip methods
show Communication fields
show CommunicationChannelType fields
show CommChannelRoleType fields

class Document<<Thing>> {
}
class Paperclip<<Role>> {
    roleName()
}

enum CommunicationChannelType<<Desc>> {
    EMAIL
}
enum CommChannelRoleType<<Desc>> {
    TO
    CC
    BCC
    FROM
}

class Communication<<MomentOfTime>> {
    subject
    atPath
    sent
}

class CommChannelRole<<Role>> {
}
class CommunicationChannel<<Thing>> {
}
class EmailCommunicationChannel<<Thing>> {
}
class PaperclipForCommunication<<Role>> {
}

Document <-down-> "0..*" Paperclip
Paperclip ^-down- PaperclipForCommunication
Communication "0..*" <-right- PaperclipForCommunication : attachedTo <

Communication -right-> "1..*" CommChannelRole

CommChannelRole -up-> CommChannelRoleType
CommChannelRole -right-> CommunicationChannel

CommunicationChannel ^-down-EmailCommunicationChannel
Communication -up-> CommunicationChannelType
--

(The colours used in the diagram are - approximately - from link:https://en.wikipedia.org/wiki/Object_Modeling_in_Color[Object Modeling in Color]).


== Document_email mixin


Uses the SPI service `DocumentEmailSupportService` (below).



== SPI Services

=== DocumentEmailSupportService

[source,java]
----
public interface DocumentEmailSupportService {
    DocumentType blankDocumentType();               // <1>
    void inferHeaderFor(                            // <2>
        Document document,
        EmailHeader header
    );
}
----
<1> A `DocumentType` with applicable `DocumentTemplate` that uses the `RenderingStrategy` with the `RendererUsesDataModelAsOutput` strategy (ie passes the input text verbatim as output).
<2> Populate the provided `EmailHeader` based on the `Document` (eg by inspecting any attachments/``Paperclip``s).

where `EmailHeader` in turn is:

[source,java]
----
public class EmailHeader {
    @Getter @Setter
    private String subject;
    @Getter
    private final Set<EmailAddress> toSet = Sets.newTreeSet();
    @Getter
    private final Set<EmailAddress> ccSet = Sets.newTreeSet();
    @Getter
    private final Set<EmailAddress> bccSet = Sets.newTreeSet();
    @Getter @Setter
    private EmailAddress from;
}
----

