= CAPEX Sketch
:Notice: (c) 2017 Eurocommercial Properties Ltd.  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:toc: right
:_basedir: ./

== Sketch

:graphvizdot: c:\Program Files (x86)\Graphviz2.38\bin\dot.exe

[plantuml,invoices,png]
--
hide empty members


''''''''''''''''''''''''''''''''''''''''''''''

interface FinancialItem << Fact >> #yellow {
    startDate: LocalDate
    endDate: LocalDate
    value(): BigDecimal
}


''''''''''''''''''''''''''''''''''''''''''''''

class CodaElement5 #cyan {
    el5Code
}

FinancialItem <--> "0..*" CodaElement5

''''''''''''''''''''''''''''''''''''''''''''''

class Tax << Dimension >> #cyan {

}

Tax "parent\n/child" <---> Tax

''''''''''''''''''''''''''''''''''''''''''''''

enum Applicability #cyan  {
    INCOMING
    OUTGOING
    IN_AND_OUT
    supportsIncoming()
    supportsOutgoing()
}

class ChargeGroup #cyan {
    reference
}


class Charge << Dimension >> #cyan {
    reference
    externalReference
}
note right #lightgray: tax,\nexternalReference,\nand chargeGroup\nare applicable\nonly to outgoing


Charge "parent/\nchild" <---> Charge
Tax <-.- Charge
ChargeGroup <-.- Charge
Applicability <-.- Charge



''''''''''''''''''''''''''''''''''''''''''''''

class Project << Dimension >> #lightgreen {
}

class ProjectItem #lightgreen implements FinancialItem {
}

Project "parent\n/child" <---> Project

Project <--> "0..*" ProjectItem



''''''''''''''''''''''''''''''''''''''''''''''

class FixedAsset << Dimension >> #lightgreen {
}


FixedAsset "parent\n/child" <---> FixedAsset



''''''''''''''''''''''''''''''''''''''''''''''

class ServiceChargeBudget #lightgreen {
    financialYear
}


ServiceChargeBudget <--> "0..*" ServiceChargeBudgetItem

FixedAsset <-- ServiceChargeBudget

class ServiceChargeBudgetItem #lightgreen implements FinancialItem {
}




''''''''''''''''''''''''''''''''''''''''''''''
class Party #lightgreen {

}
note right #lightgray: eventually expect Party\nto also be 1 or 2 dimensions\n(debtor and/or creditor)

Party "\n\n\nbuyer" <-- Invoice
Party "\n\n\n  seller" <-- Invoice




''''''''''''''''''''''''''''''''''''''''''''''

class Order #lightgreen  {
    entryDate
    orderDate
    orderNumber
    approvedOn
    approvedBy
}

class OrderItem #lightgreen implements FinancialItem {
    startDate
    endDate
    description
    netAmount: BigDecimal
    vatAmount: BigDecimal
    grossAmount: BigDecimal
    charge: Charge
    tax: Tax
    property: Property
    project: Project
}

class PaperclipForOrder #lightgreen {

}

Order <--> "0..*" OrderItem


Party "buyer" <-- Order
Party "seller" <-- Order


Document <-- "0..1         " PaperclipForOrder
Order <-- PaperclipForOrder



''''''''''''''''''''''''''''''''''''''''''''''

abstract class Invoice #pink {
    dueDate: LocalDate
    invoiceDate: LocalDate
    amount: BigDecimal
}

enum PaymentMethod #cyan  {
    DIRECT_DEBIT,
    BILLING_ACCOUNT,
    BANK_TRANSFER,
    CASH,
    CHEQUE
}


class IncomingInvoice #pink extends Invoice  {
    received: LocalDate
    status
}

class BankAccount #lightgreen {

}

class PaperclipForBankAccount #lightgreen {

}




class IncomingInvoiceItem #pink  implements FinancialItem  {
}


class OrderItemInvoiceItemLink #pink {

}


' some invoices will have credit note(s) pointing back to them
IncomingInvoice "0..1" <-- "credit note" IncomingInvoice


IncomingInvoiceItem <--- OrderItemInvoiceItemLink
OrderItem <--- OrderItemInvoiceItemLink

IncomingInvoice *---> "1..*" IncomingInvoiceItem
PaymentMethod <--- IncomingInvoice


BankAccount <-- IncomingInvoice

Document <-- "0..1         " PaperclipForBankAccount
BankAccount <-- PaperclipForBankAccount


class Document #lightgreen {

}


class PaperclipForIncomingInvoice #pink {

}

Document <-- "0..1         " PaperclipForIncomingInvoice
IncomingInvoice <-- PaperclipForIncomingInvoice


''''''''''''''''''''''''''''''''''''''''''''''


class Payment #lightgreen {
    amount: BigDecimal
}
note right #lightgray: payment method\nnot necessarily\nsame as that\nof invoice





IncomingInvoice "payment" <--- "0..* " Payment
note left #lightgray: can only refer to invoices,\nnot credit notes.\nif invoice has credit notes,\nthen we also derive\nthat the payment pays off\na those credit notes also



PaymentMethod <--- Payment





''''''''''''''''''''''''''''''''''''''''''''''

enum FinancialItemType #cyan  {
    BUDGETED
    ORDERED
    INVOICED
}

Project <-.- FinancialItem
FixedAsset <-.- FinancialItem
Tax <-.- FinancialItem
Charge <--- FinancialItem
FinancialItemType <-- FinancialItem




--

Sketched/placeholders:

* CODA Element5 mappings
* Payment lines

Not yet in scope:

* Order needs to link to Document
* approvals workflow (perhaps: tasks/actors/orgunits/employees)



== FinancialItem

Responsibilities:

[graphviz,_images/financial-item-responsibilities,png]
----
digraph {
  node[shape=Mrecord]
  FRANCE;
  FRANCE -> LEGAL ;
  FRANCE -> MARKETING ;
  FRANCE -> ARCHITECT ;

  FRANCE [label="{<f0> FRANCE|<f1> value=1,000,000\nrolledUp=225,000\nremaining=775,000}" ];
  LEGAL [label="{<f0> LEGAL|<f1> value=50,000}" ];
  MARKETING [label="{<f0> LEGAL|<f1> value=100,000}" ];
  ARCHITECT [label="{<f0> LEGAL|<f1> value=75,000}" ];
}
----

== State charts

[plantuml,state-charts,png]
--

state "IncomingDocumentCategorisationStateTransitionType" as idc {
    state "NEW" as idc_new
    state "CATEGORISED_AND_\nASSOCIATED_WITH_PROPERTY" as idc_caawp
    state "ASSOCIATED_\nWITH_DOMAIN_ENTITY" as idc_awde

    [*] --> idc_new: INSTANTIATING
    idc_new --> idc_caawp : CATEGORISE_DOCUMENT_TYPE_AND_\nASSOCIATE_WITH_PROPERTY
    idc_caawp --> idc_awde : ASSOCIATE_WITH_DOMAIN_ENTITY
    idc_awde -down-> [*]
}

[*] --> idc
idc --> a : IncomingInvoiceApprovalInitiatorSubscribingToUpstreamDocumentState

state "Invoice Approval" as a {

    state "IncomingInvoice\nApproval\nStateTransitionType" as iia {

        state "Approval" as iia_a {
            state "NEW" as iia_a_new
            state "APPROVED_BY_ \n PROJECT_MANAGER" as iia_a_abpm
            state "APPROVED_BY_ \n ASSET_MANAGER" as iia_a_abam
            state "APPROVED_BY_ \n COUNTRY_DIRECTOR" as iia_a_abcd

            [*] --> iia_a_new : INSTANTIATE
            iia_a_new --> iia_a_abpm : APPROVE_AS_\nPROJECT_MANAGER\n[hasProject]
            iia_a_new --> iia_a_abam : APPROVE_AS_\nASSET_MANAGER\n[else]
            iia_a_abpm --> iia_a_abcd : APPROVE_AS_\nCOUNTRY_DIRECTOR
            iia_a_abam --> iia_a_abcd
            iia_a_abcd --> [*]
        }
        state "CANCELLED" as iia_cancelled

        [*] --> iia_a
        iia_a --> iia_cancelled : CANCEL
        iia_a --> [*]
    }
    [*] --> iia
    ||
    state "BankAccount\nVerification\nStateTransitionType" as bbv {
        state "PENDING" as bbv_pending
        state "VERIFIED" as bbv_verified
        state "CANCELLED" as bbv_cancelled

        [*] --> bbv_pending: INSTANTIATE
        bbv_pending --> bbv_verified: VERIFY_\nBANK_ACCOUNT
        bbv_pending --> bbv_cancelled: CANCEL
        bbv_verified --> [*]
    }
    [*] --> bbv : [new bank account to verify]
}

state "PaymentProcessing" as pp {
    state "NEW" as pp_new
    state "APPROVED_BY_ \n TREASURER" as pp_abt
    state "CANCELLED" as pp_c

    [*] --> pp_new : INSTANTIATE
    pp_new --> pp_abt : APPROVE_AS_\nTREASURER\n[bank account verified]
    pp_new --> pp_c : CANCEL
    pp_abt --> [*]
}

a --> pp : PaymentApprovalInitiatorSubscribingToIncomingInvoiceApprovalStateTransition
--