= CAPEX Sketch
:Notice: (c) 2017 Eurocommercial Properties Ltd.  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:toc: right
:_basedir: ./

== Sketch

:graphvizdot: c:\Program Files (x86)\Graphviz2.38\bin\dot.exe

[plantuml,invoices,png]
--
hide empty members


''''''''''''''''''''''''''''''''''''''''''''''

interface FinancialItem << Fact >> #yellow {
    startDate: LocalDate
    endDate: LocalDate
    value(): BigDecimal
}


''''''''''''''''''''''''''''''''''''''''''''''

class CodaElement5 #cyan {
    el5Code
}

FinancialItem <--> "0..*" CodaElement5

''''''''''''''''''''''''''''''''''''''''''''''

class Tax << Dimension >> #cyan {

}

Tax "parent\n/child" <---> Tax

''''''''''''''''''''''''''''''''''''''''''''''

enum Applicability #cyan  {
    INCOMING
    OUTGOING
    IN_AND_OUT
    supportsIncoming()
    supportsOutgoing()
}

class ChargeGroup #cyan {
    reference
}


class Charge << Dimension >> #cyan {
    reference
    externalReference
}
note right #lightgray: tax,\nexternalReference,\nand chargeGroup\nare applicable\nonly to outgoing


Charge "parent/\nchild" <---> Charge
Tax <-.- Charge
ChargeGroup <-.- Charge
Applicability <-.- Charge



''''''''''''''''''''''''''''''''''''''''''''''

class Project << Dimension >> #lightgreen {
}

class ProjectItem #lightgreen implements FinancialItem {
}

Project "parent\n/child" <---> Project

Project <--> "0..*" ProjectItem



''''''''''''''''''''''''''''''''''''''''''''''

class FixedAsset << Dimension >> #lightgreen {
}


FixedAsset "parent\n/child" <---> FixedAsset



''''''''''''''''''''''''''''''''''''''''''''''

class ServiceChargeBudget #lightgreen {
    financialYear
}


ServiceChargeBudget <--> "0..*" ServiceChargeBudgetItem

FixedAsset <-- ServiceChargeBudget

class ServiceChargeBudgetItem #lightgreen implements FinancialItem {
}




''''''''''''''''''''''''''''''''''''''''''''''
class Party #lightgreen {

}
note right #lightgray: eventually expect Party\nto also be 1 or 2 dimensions\n(debtor and/or creditor)

Party "\n\n\nbuyer" <-- Invoice
Party "\n\n\n  seller" <-- Invoice




''''''''''''''''''''''''''''''''''''''''''''''

class Order #lightgreen  {
    entryDate
    orderDate
    orderNumber
    approvedOn
    approvedBy
}

class OrderItem #lightgreen implements FinancialItem {
    startDate
    endDate
    description
    netAmount: BigDecimal
    vatAmount: BigDecimal
    grossAmount: BigDecimal
    charge: Charge
    tax: Tax
    property: Property
    project: Project
}

Order <--> "0..*" OrderItem


Party "buyer" <-- Order
Party "seller" <-- Order




''''''''''''''''''''''''''''''''''''''''''''''

abstract class Invoice #pink {
    dueDate: LocalDate
    invoiceDate: LocalDate
    amount: BigDecimal
}

enum PaymentMethod #cyan  {
    DIRECT_DEBIT,
    BILLING_ACCOUNT,
    BANK_TRANSFER,
    CASH,
    CHEQUE
}


class IncomingInvoice #pink extends Invoice  {
    received: LocalDate
    status
}

class BankAccount #lightgreen {

}



class IncomingInvoiceItem #pink  implements FinancialItem  {
}


class OrderItemInvoiceItemLink #pink {

}

IncomingInvoiceItem <--- OrderItemInvoiceItemLink
OrderItem <--- OrderItemInvoiceItemLink

IncomingInvoice *---> "1..*" IncomingInvoiceItem
PaymentMethod <--- IncomingInvoice


BankAccount <-- IncomingInvoice


class Document #lightgreen {

}


class PaperclipForIncomingInvoice #pink {

}

Document <-- "0..1         " PaperclipForIncomingInvoice
IncomingInvoice <-- PaperclipForIncomingInvoice


''''''''''''''''''''''''''''''''''''''''''''''


class Payment #lightgreen {
    amount: BigDecimal
    paidOn: LocalDate
}
note right #lightgray: payment method\nnot necessarily\nsame as that\nof invoice


IncomingInvoice <--- "0..* " Payment

PaymentMethod <--- Payment





''''''''''''''''''''''''''''''''''''''''''''''

enum FinancialItemType #cyan  {
    BUDGETED
    ORDERED
    INVOICED
}

Project <-.- FinancialItem
FixedAsset <-.- FinancialItem
Tax <-.- FinancialItem
Charge <--- FinancialItem
FinancialItemType <-- FinancialItem




--

Sketched/placeholders:

* CODA Element5 mappings
* Payment lines

Not yet in scope:

* Order needs to link to Document
* approvals workflow (perhaps: tasks/actors/orgunits/employees)



== FinancialItem

Responsibilities:

[graphviz,_images/financial-item-responsibilities,png]
----
digraph {
  node[shape=Mrecord]
  FRANCE;
  FRANCE -> LEGAL ;
  FRANCE -> MARKETING ;
  FRANCE -> ARCHITECT ;

  FRANCE [label="{<f0> FRANCE|<f1> value=1,000,000\nrolledUp=225,000\nremaining=775,000}" ];
  LEGAL [label="{<f0> LEGAL|<f1> value=50,000}" ];
  MARKETING [label="{<f0> LEGAL|<f1> value=100,000}" ];
  ARCHITECT [label="{<f0> LEGAL|<f1> value=75,000}" ];
}
----
