= CAPEX State Charts
:Notice: (c) 2017 Eurocommercial Properties Ltd.  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:toc: right
:_basedir: ./



== Incoming Document Categorisation

[plantuml,document-categorisation-state-chart,png]
--
state "IncomingDocumentCategorisationStateTransitionType" as idc {

    state "NEW" as idc_new
    state "CATEGORISED" as idc_c
    state "DISCARDED" as idc_d

    [*] -right-> idc_new: INSTANTIATE
    idc_new -down-> idc_c : CATEGORISE
    idc_c -up-> idc_new : \n\n\n RESET\n\n\n
    idc_c -right-> idc_d : \n\n        DISCARD_ASSOCIATED \n       (when associated invoice\n     or order is discarded)
    idc_new --> idc_d : \nDISCARD\n(explicit)
}
--

== Incoming Invoice Approval

The lightgreen states have an advancePolicy of "AUTOMATIC", meaning that the state transition will proceed directly through provided that any corresponding `autoGuard` is satisfied.

[plantuml,incoming-invoice-approval-state-chart,png]
--
state "IncomingInvoiceApprovalStateTransitionType" as iia {

    skinparam state {
      BackgroundColor<<Automatic>> lightgreen
    }

    state "NEW" as iia_new

    state "DISCARDED" as iia_discarded
    note right of iia_discarded: associated document\nalso discarded

    state "pending" as iia_pp {
        state "COMPLETED" as iia_completed

        state "APPROVED" as iia_a<<Automatic>>

        state "final approval" as iia_final {
            state "APPROVED_BY_ \n COUNTRY_DIRECTOR" as iia_abcd<<Automatic>>
            state "APPROVED_BY_ \n CORPORATE_MANAGER" as iia_abcm<<Automatic>>
        }
        note left of iia_final: mutable only\nprior to\nthis state

        state "PENDING_BANK_\nACCOUNT_CHECK" as iia_pbac<<Automatic>>
        state "PAYABLE" as iia_payable
    }

    state "PAID" as iia_paid

    [*] -right-> iia_new: INSTANTIATE

    iia_new --> iia_completed : COMPLETE\nmatch: [hasProperty() |  local | corporate ] \nguard: [ reasonIncomplete() != null ]
    iia_new -right-> iia_discarded : DISCARD

    iia_completed --> iia_a : APPROVE   \nmatch: [capex | asset | services_charges ]       \nguard: [ reasonIncomplete() != null ]\nautoGuard: [ approvedFully ]

    iia_completed -r-> iia_abcd : \n\n\nAPPROVE_LOCAL_AS_\nCOUNTRY_DIRECTOR\nmatch: [local]\nautoGuard: [ approvedFully ]
    iia_completed --> iia_abcm : APPROVE_AS_\nCORPORATE_MANAGER       \nmatch: [corporate]\nautoGuard: [ approvedFully ]

    iia_a --> iia_abcd : APPROVE_AS_\nCOUNTRY_DIRECTOR\nautoGuard: [ approvedFully ]
    
    iia_final --> iia_pbac : CHECK_BANK_ACCOUNT

    iia_pp --> iia_new: \n  REJECT

    iia_pbac --> iia_payable : CONFIRM_BANK_ACCOUNT_VERIFIED\n guard: [bank account verified || paymentMethod="DIRECT_DEBIT" ]
    iia_payable --> iia_paid: PAY_BY_IBP\nmatch: [paymentMethod = \n            "BANK_TRANSFER"]
    iia_payable --> iia_paid: PAY_BY_IBP_MANUAL\nmatch: [paymentMethod = \n             "MANUAL_PROCESS"]
    iia_payable --> iia_paid: PAY_BY_DD\n  match: [paymentMethod=\n            "DIRECT_DEBIT"]

}
--

== Order Approval

[plantuml,order-approval-state-chart,png]
--
state "OrderApprovalStateTransitionType" as oa {

    state "NEW" as oa_new

    state "APPROVED" as oa_approved
    note right of oa_approved: immutable at this point on

    state "DISCARDED" as oa_discarded
    note right of oa_discarded: associated document\nalso discarded

    [*] -right-> oa_new: INSTANTIATE

    oa_new -down-> oa_approved: COMPLETE_WITH_APPROVAL
    oa_approved -up-> oa_new: FIX_ERROR
    oa_new -right-> oa_discarded : DISCARD

}
--


== Bank Account Verification

[plantuml,bank-account-verification-state-chart,png]
--
state "BankAccountVerificationStateTransitionType" as bbv {

    state "NOT_VERIFIED" as bbv_not_verified
    state "VERIFIED" as bbv_verified

    [*] --right--> bbv_not_verified: \n  INSTANTIATE
    bbv_not_verified -down--> bbv_verified: VERIFY_\nBANK_ACCOUNT

}
--


== Payment Batch Authorisation

[plantuml,payment-approval-state-chart,png]
--
state "PaymentBatchApprovalStateTransitionType" as pa {

    state "NEW" as pa_new
    state "COMPLETED" as pa_completed
    state "PAID" as pa_paid
    state "DISCARDED" as pa_discarded

    [*] -right-> pa_new: INSTANTIATE
    pa_new -down-> pa_completed: COMPLETE\n (as treasurer)
    pa_completed -down-> pa_paid: CONFIRM_AUTHORISATION\n (in IBP, as financial director)
    pa_completed -right-> pa_discarded: DISCARD

}
--

Notes:

* the incoming invoice state chart is now instantiated via a lifecycle event on invoice (rather than, as previously, listening to the document moving to a 'processed' state)

* ditto bank account's verification state chart

* After bank account verified, respective subscribers update any incoming invoices approved but awaiting verification before moving to `PAID`state
