= CAPEX Sketch
:Notice: (c) 2017 Eurocommercial Properties Ltd.  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:toc: right
:_basedir: ./

== Sketch



[plantuml,invoices,png]
--
hide empty members

''''''''''''''''''''''''''''''''''''''''''''''
class FixedAsset #lightgreen {
}


FixedAsset "parent/child" <---> FixedAsset

''''''''''''''''''''''''''''''''''''''''''''''

class IncomingCharge #cyan {
}

show IncomingCharge members

IncomingCharge "parent/child" <---> IncomingCharge

''''''''''''''''''''''''''''''''''''''''''''''

class CodaElement5 #lightgray {
    el5Code
}
note right #lightgray: additional\ndimensions \nto be identified

IncomingCharge <--> "0..*" CodaElement5


''''''''''''''''''''''''''''''''''''''''''''''


class Project #cyan {
}

Project "parent/child" <---> Project

class Budget #lightgreen {
    financialYear: DateTime
}

enum ItemValueType #cyan {
    BUDGETED
    ORDERED
    INVOICED
}

interface ItemValue #yellow {
    value(): BigDecimal
    rolledUp(): BigDecimal
    remaining(): BigDecimal
}



'Project <--> "0..*" Budget

Budget <--> "0..*" BudgetItem


'IncomingCharge <-- BudgetItem

Project "     0..1" <-- ItemValue
FixedAsset "0..1" <-- ItemValue
Interval <-- ItemValue
IncomingCharge <-- ItemValue

ItemValueType <-- ItemValue

''''''''''''''''''''''''''''''''''''''''''''''

class BudgetItem #lightgreen implements ItemValue {
}



''''''''''''''''''''''''''''''''''''''''''''''
class Party #lightgreen {
}


Party "buyer  " <-- Invoice
Party "\nseller" <-- Invoice


''''''''''''''''''''''''''''''''''''''''''''''

class Order #lightgreen  {
}

class OrderItem #lightgreen implements ItemValue {
    
}

Order <--> "0..*" OrderItem

/'
class PurchaseOrder #lightgreen extends Order {
}
class SupplierProposal #lightgreen extends Order {
    approved: boolean
}
'/

Party "  supplier" <-- Order



''''''''''''''''''''''''''''''''''''''''''''''
class Interval #cyan {
    
}

Interval "parent/child" <---> Interval


''''''''''''''''''''''''''''''''''''''''''''''

abstract class Invoice #pink {
    dueDate: Date
    invoiceDate: Date
    amount: BigDecimal
}

class IncomingInvoice #pink extends Invoice  {
    received: Date
}

abstract class InvoiceItem #pink {
}

class IncomingInvoiceItem #pink extends InvoiceItem implements ItemValue  {

}

'IncomingCharge <-- IncomingInvoiceItem

Invoice *---> "1..*  " InvoiceItem

OrderItem <-- IncomingInvoiceItem





''''''''''''''''''''''''''''''''''''''''''''''
class Document #lightgreen {
}


'FixedAsset <-- IncomingInvoiceItem

IncomingInvoice --> Document


''''''''''''''''''''''''''''''''''''''''''''''
class PaymentLine #lightgray {
}
note right #lightgray: just a\nsketch

IncomingInvoice --> "0..*" PaymentLine
'PaymentLine "0..*" <-- IncomingInvoice


--

Sketched/placeholders:

* CODA Element5 mappings
* Payment lines

Not yet in scope:

* Order needs to link to Document
* approvals workflow (perhaps: tasks/actors/orgunits/employees)
