= CAPEX Sketch
:Notice: (c) 2017 Eurocommercial Properties Ltd.  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:toc: right
:_basedir: ./

== Sketch

:graphvizdot: c:\Program Files (x86)\Graphviz2.38\bin\dot.exe

[plantuml,invoices,png]
--
hide empty members

''''''''''''''''''''''''''''''''''''''''''''''
class FixedAsset << Dimension >> #lightgreen {
}


FixedAsset "parent/child" <---> FixedAsset

''''''''''''''''''''''''''''''''''''''''''''''

class IncomingCharge << Dimension >> #cyan {
}

show IncomingCharge members

IncomingCharge "parent/child" <---> IncomingCharge

''''''''''''''''''''''''''''''''''''''''''''''

class CodaElement5 #lightgray {
    el5Code
}
note right #lightgray: additional\ndimensions \nto be identified

IncomingCharge <--> "0..*" CodaElement5


''''''''''''''''''''''''''''''''''''''''''''''


class Project << Dimension >> #cyan {
}

class ProjectItem #cyan implements FinancialItem {
}

Project "parent/child" <---> Project

Project <--> "0..*" ProjectItem

class ServiceChargeBudget #lightgreen {
    financialYear: DateTime
}

enum FinancialItemType #cyan  {
    BUDGETED
    ORDERED
    INVOICED
}

interface FinancialItem << Fact >> #yellow {
    value(): BigDecimal
    rolledUp(): BigDecimal
    remaining(): BigDecimal
}



'Project <--> "0..*" ServiceChargeBudget

ServiceChargeBudget <--> "0..*" ServiceChargeBudgetItem


'IncomingCharge <-- ServiceChargeBudgetItem

Project "     0..1" <-- FinancialItem
FixedAsset "0..1" <-- FinancialItem
Interval <-- FinancialItem
IncomingCharge <-- FinancialItem

FinancialItemType <-- FinancialItem

FixedAsset <-- ServiceChargeBudget

class OrderInvoiceLink #pink {

}

OrderItem <-- OrderInvoiceLink
IncomingInvoiceItem <-- OrderInvoiceLink

''''''''''''''''''''''''''''''''''''''''''''''

class ServiceChargeBudgetItem #lightgreen implements FinancialItem {
}



''''''''''''''''''''''''''''''''''''''''''''''
class Party #lightgreen {
}


Party "buyer  " <-- Invoice
Party "\nseller" <-- Invoice


''''''''''''''''''''''''''''''''''''''''''''''

class Order #lightgreen  {
}

class OrderItem #lightgreen implements FinancialItem {
    
}

Order <--> "0..*" OrderItem

/'
class PurchaseOrder #lightgreen extends Order {
}
class SupplierProposal #lightgreen extends Order {
    approved: boolean
}
'/

Party "  supplier" <-- Order



''''''''''''''''''''''''''''''''''''''''''''''
class Interval << Dimension >>  #cyan {
    
}

Interval "parent/child" <---> Interval


''''''''''''''''''''''''''''''''''''''''''''''

abstract class Invoice #pink {
    dueDate: Date
    invoiceDate: Date
    amount: BigDecimal
}

class IncomingInvoice #pink extends Invoice  {
    received: Date
}

abstract class InvoiceItem #pink {
}

class IncomingInvoiceItem #pink extends InvoiceItem implements FinancialItem  {

}

class Tax << Dimension >> #cyan {

}

Tax "parent/child" <---> Tax


'IncomingCharge <-- IncomingInvoiceItem

Invoice *---> "1..*  " InvoiceItem

Tax "0..1" <-- FinancialItem




''''''''''''''''''''''''''''''''''''''''''''''
class Document #lightgreen {
}


'FixedAsset <-- IncomingInvoiceItem

IncomingInvoice --> Document


''''''''''''''''''''''''''''''''''''''''''''''
class PaymentLine #lightgray {
}
note right #lightgray: just a\nsketch

IncomingInvoice --> "0..*" PaymentLine
'PaymentLine "0..*" <-- IncomingInvoice


--

Sketched/placeholders:

* CODA Element5 mappings
* Payment lines

Not yet in scope:

* Order needs to link to Document
* approvals workflow (perhaps: tasks/actors/orgunits/employees)
