= CAPEX Sketch
:Notice: (c) 2017 Eurocommercial Properties Ltd.  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:toc: right
:_basedir: ./

== Sketch

:graphvizdot: c:\Program Files (x86)\Graphviz2.38\bin\dot.exe

[plantuml,invoices,png]
--
hide empty members


''''''''''''''''''''''''''''''''''''''''''''''

interface FinancialItem << Fact >> #yellow {
    value(): BigDecimal
    rolledUp(): BigDecimal
    remaining(): BigDecimal
}

enum FinancialItemType #cyan  {
    BUDGETED
    ORDERED
    INVOICED
}

FinancialItemType <-- FinancialItem

''''''''''''''''''''''''''''''''''''''''''''''

class CodaElement5 #pink {
    el5Code
}
note right #lightgray: fact + its dimensions\nmap to Coda

FinancialItem <--> "0..*" CodaElement5

''''''''''''''''''''''''''''''''''''''''''''''

class IncomingCharge << Dimension >> #cyan {
}


IncomingCharge "parent/child" <---> IncomingCharge



''''''''''''''''''''''''''''''''''''''''''''''
enum CalendarType #cyan {
    NATURAL,
    FINANCIAL
}

class TimeInterval << Dimension >>  #cyan {
    name: String  
    startDate: Date
    endDate: Date
}
note right #lightgray: both calendar\nand financial\ntime intervals\neg F2014, 2015Q1,\neg 2015-03, 2015-03-17\nand two hierarchies

TimeInterval "parent/child\n" <---> TimeInterval

CalendarType <-- TimeInterval

''''''''''''''''''''''''''''''''''''''''''''''

class Tax << Dimension >> #cyan {

}

Tax "parent/child" <---> Tax



''''''''''''''''''''''''''''''''''''''''''''''

class Project << Dimension >> #lightgreen {
}

class ProjectItem #lightgreen implements FinancialItem {
}

Project "parent/child" <---> Project

Project <--> "0..*" ProjectItem



''''''''''''''''''''''''''''''''''''''''''''''

class FixedAsset << Dimension >> #lightgreen {
}


FixedAsset "parent/child" <---> FixedAsset



''''''''''''''''''''''''''''''''''''''''''''''

class ServiceChargeBudget #lightgreen {
    financialYear
}


ServiceChargeBudget <--> "0..*" ServiceChargeBudgetItem

FixedAsset <-- ServiceChargeBudget

class ServiceChargeBudgetItem #lightgreen implements FinancialItem {
}




''''''''''''''''''''''''''''''''''''''''''''''
class Party #lightgreen {
}
note right #lightgray: eventually expect Party\nto also be 1 or 2 dimensions\n(debtor and/or creditor)

Party "buyer  " <-- Invoice
Party "\nseller" <-- Invoice


''''''''''''''''''''''''''''''''''''''''''''''

class Order #lightgreen  {
}

class OrderItem #lightgreen implements FinancialItem {
    
}

Order <--> "0..*" OrderItem


Party "  supplier" <-- Order



''''''''''''''''''''''''''''''''''''''''''''''

abstract class Invoice #pink {
    dueDate: Date
    invoiceDate: Date
    amount: BigDecimal
}

class IncomingInvoice #pink extends Invoice  {
    received: Date
}


class IncomingInvoiceItem #pink  implements FinancialItem  {
}


IncomingInvoice *---> "1..*  " IncomingInvoiceItem



class Document #lightgreen {
}


IncomingInvoice --> Document


class PaymentLine #lightgray {
}


IncomingInvoice --> "0..*" PaymentLine


''''''''''''''''''''''''''''''''''''''''''''''

class OrderInvoiceLink #pink {

}

OrderItem <-- OrderInvoiceLink
IncomingInvoiceItem <-- OrderInvoiceLink

''''''''''''''''''''''''''''''''''''''''''''''


Project <-.- FinancialItem
FixedAsset <-.- FinancialItem
Tax <-.- FinancialItem
IncomingCharge <--- FinancialItem
TimeInterval "natural" <--- FinancialItem
TimeInterval "financial" <--- FinancialItem



--

Sketched/placeholders:

* CODA Element5 mappings
* Payment lines

Not yet in scope:

* Order needs to link to Document
* approvals workflow (perhaps: tasks/actors/orgunits/employees)
