= CAPEX State Charts
:Notice: (c) 2017 Eurocommercial Properties Ltd.  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:toc: right
:_basedir: ./



== Incoming Document Categorisation

[plantuml,document-categorisation-state-chart,png]
--
state "IncomingDocumentCategorisationStateTransitionType" as idc {

    state "NEW" as idc_new
    state "CATEGORISED" as idc_c

    [*] -right-> idc_new: INSTANTIATE
    idc_new -down-> idc_c : \n  CATEGORISE
}
--

== Incoming Invoice Approval

[plantuml,incoming-invoice-approval-state-chart,png]
--
state "IncomingInvoice\nApproval\nStateTransitionType" as iia {

    state "NEW" as iia_new
    note right of iia_new: currently no transitions for\nTANGIBLE_FIXED_ASSET, INTERCOMPANY, RE_INVOICING,


    state "COMPLETED" as iia_completed
    note right of iia_completed: immutable from this point on

    state "APPROVED" as iia_a
    state "APPROVED_BY_ \n COUNTRY_DIRECTOR" as iia_abcd
    
    state "PENDING_BANK_\nACCOUNT_CHECK" as iia_pbac

    state "PAYABLE" as iia_payable
    state "PAID" as iia_paid

    [*] -right-> iia_new: INSTANTIATE

    iia_new -down-> iia_completed : COMPLETE_\nPROPERTY_\nINVOICE\n[capex || property ||\nservice || legal]
    iia_new -down-> iia_completed : COMPLETE_\nLOCAL_\nINVOICE\n[local]
    iia_new -down-> iia_completed : COMPLETE_\nCORPORATE_\nINVOICE\n[corporate]

    iia_completed --> iia_a : APPROVE_AS_\nLEGAL_MANAGER\n[legal]
    iia_completed --> iia_a : APPROVE_AS_\nPROJECT_MANAGER\n[capex]
    iia_completed --> iia_a : APPROVE_AS_\nASSET_MANAGER\n[asset]

    iia_completed --> iia_abcd : APPROVE_\nLOCAL_AS\n_COUNTRY_DIRECTOR\n[local]
    iia_completed --> iia_pbac : CHECK_BANK_ACCOUNT_\nFOR_CORPORATE\n[corporate]
    
    iia_a -down-> iia_abcd : APPROVE_AS_\nCOUNTRY_DIRECTOR
    
    iia_abcd --> iia_pbac : CHECK_BANK_ACCOUNT

    iia_pbac --> iia_payable : CONFIRM_\nBANK_ACCOUNT_\nVERIFIED\n [bank account verified ||\n direct debit]
    iia_payable --> iia_paid: PAY_BY_IBQ\n[paymentMethod=\n"BANK_TRANSFER"]
    iia_payable --> iia_paid: PAY_BY_DD\n[paymentMethod=\n"DIRECT_DEBIT"]
}
--

== Bank Account Verification

[plantuml,bank-account-verification-state-chart,png]
--
state "BankAccount\nVerification\nStateTransitionType" as bbv {

    state "NOT_VERIFIED" as bbv_not_verified
    state "VERIFIED" as bbv_verified

    [*] --right--> bbv_not_verified: \n  INSTANTIATE
    bbv_not_verified -down--> bbv_verified: VERIFY_\nBANK_ACCOUNT

}
--


== Payment Approval

[plantuml,payment-approval-state-chart,png]
--
state "PaymentApproval\nStateTransitionType" as pa {

    state "NEW" as pa_new
    state "APPROVED" as pa_approved

    [*] -right-> pa_new: INSTANTIATE
    pa_new -down-> pa_approved: APPROVED

}
--

Notes:

* the incoming invoice state chart is now instantiated via a lifecycle event on invoice (rather than, as previously, listening to the document moving to a 'processed' state)

* ditto bank account's verification state chart

* After bank account verified, respective subscribers update any incoming invoices approved but awaiting verification before moving to `PAID`state
