 = CAPEX State Charts
:Notice: (c) 2017 Eurocommercial Properties Ltd.  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:toc: right
:_basedir: ./


[plantuml,state-charts,png]
--
state "IncomingDocumentCategorisationStateTransitionType" as idc {

    state "NEW" as idc_new
    state "CATEGORISED_AND_\nASSOCIATED_WITH_PROPERTY" as idc_caawp

    state "CLASSIFIED_AS_\nINVOICE_OR_ORDER" as idc_awde

    [*] -right-> idc_new: INSTANTIATE
    idc_new -down-> idc_caawp : CATEGORISE_  \nDOCUMENT_TYPE_  \nAND_ASSOCIATE_  \nWITH_PROPERTY
    idc_caawp -up-> idc_new :  \n  RESET
    idc_new -right-> [*]: /delete

    idc_caawp --> idc_awde : CLASSIFY_AS_\nINVOICE_OR_ORDER
}


state "BankAccount\nVerification\nStateTransitionType" as bbv {


    state "NOT_VERIFIED" as bbv_not_verified
    [*] -down-> bbv_not_verified: \n  INSTANTIATE

    state "VERIFIED" as bbv_verified

    bbv_verified -left-> bbv_not_verified: \n  RESET
    bbv_not_verified --> bbv_verified: VERIFY_\nBANK_ACCOUNT
}

[*] -> idc

idc_caawp -right-> bbv_not_verified : BankAccount\nVerification\nStateSubscriber\n[new bank account \nto verify]
idc_awde -> iia : IncomingInvoice\nApproval\nStateSubscriber


state "IncomingInvoice\nApproval\nStateTransitionType" as iia {

    state "Approval" as iia_a {
        state "Local Approval" as iia_la {
            state "NEW" as iia_la_new
            state "CLASSIFIED" as iia_la_classified
            state "APPROVED_BY_ \n PROJECT_MANAGER" as iia_la_abpm
            state "APPROVED_BY_ \n ASSET_MANAGER" as iia_la_abam
            state "APPROVED_BY_ \n COUNTRY_ADMINISTRATOR" as iia_la_abca

            [*] -right-> iia_la_new : INSTANTIATE
            iia_la_new --> iia_la_classified: COMPLETE_\nCLASSIFICATION\n[completely\nclassified]
            iia_la_classified --> iia_la_abam : APPROVE_AS_\nASSET_MANAGER\n[hasServiceCharges]
            iia_la_classified --> iia_la_abpm : APPROVE_AS_\nPROJECT_MANAGER\n[hasProject]
            iia_la_classified --> iia_la_abca : APPROVE_AS_\nCOUNTRY_ADMINISTRATOR\n[else]
        }

        state "APPROVED_BY_ \n COUNTRY_DIRECTOR" as iia_abcd

        iia_la_abpm -> iia_abcd
        iia_la_abam -> iia_abcd : APPROVE_AS_\nCOUNTRY_DIRECTOR
        iia_la_abca -> iia_abcd

    }
    state "PAYABLE" as iia_payable
    state "PAID" as iia_paid
    state "CANCELLED" as iia_cancelled

    iia_abcd --> iia_payable : CONFIRM_\nBANK_ACCOUNT_\nVERIFIED\n [bank account verified ||\ndirect debit]
    iia_payable --> iia_paid: PAID\n  (by IBQ or DD)
    iia_a --> iia_cancelled : CANCEL

}
bbv_verified --> iia_payable: \n  IncomingInvoice\n  Approval\n  StateSubscriber
--