= CAPEX State Charts
:Notice: (c) 2017 Eurocommercial Properties Ltd.  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:toc: right
:_basedir: ./



== Incoming Document Categorisation

[plantuml,document-categorisation-state-chart,png]
--
state "IncomingDocumentCategorisationStateTransitionType" as idc {

    state "NEW" as idc_new
    state "CATEGORISED" as idc_c
    state "DISCARDED" as idc_d

    [*] -right-> idc_new: INSTANTIATE
    idc_new -down-> idc_c : CATEGORISE\n\n
    idc_c -right-> idc_d : \n  DISCARD_ASSOCIATED \n(when associated invoice\nor order is discarded)
    idc_new --> idc_d : \n  DISCARD\n (explicit)
}
--

== Incoming Invoice Approval

[plantuml,incoming-invoice-approval-state-chart,png]
--
state "IncomingInvoiceApprovalStateTransitionType" as iia {

    state "NEW" as iia_new

    state "COMPLETED" as iia_completed
    note right of iia_completed: immutable from this point on

    state "DISCARDED" as iia_discarded
    note right of iia_discarded: associated document\nalso discarded

    state "APPROVED" as iia_a
    state "APPROVED_BY_ \n COUNTRY_DIRECTOR" as iia_abcd
    
    state "PENDING_BANK_\nACCOUNT_CHECK" as iia_pbac

    state "PAYABLE" as iia_payable
    state "PAID" as iia_paid

    [*] -right-> iia_new: INSTANTIATE

    iia_new -down-> iia_completed : COMPLETE\n[hasProperty() | \n local | corporate ]
    iia_new -right-> iia_discarded : DISCARD

    iia_completed --> iia_a : APPROVE\n[capex | \nasset | services_charges ]

    iia_completed --> iia_abcd : APPROVE_\nLOCAL_AS\n _COUNTRY_DIRECTOR\n[local]
    iia_completed --> iia_pbac : CHECK_BANK_ACCOUNT_\n FOR_CORPORATE\n[corporate]
    
    iia_a -down-> iia_abcd : APPROVE_AS_\nCOUNTRY_DIRECTOR
    
    iia_abcd --> iia_pbac : CHECK_BANK_ACCOUNT

    iia_pbac --> iia_payable : CONFIRM_\nBANK_ACCOUNT_\nVERIFIED\n [bank account verified ||\n direct debit]
    iia_payable --> iia_paid: PAY_BY_IBP\n[paymentMethod=\n"BANK_TRANSFER"]
    iia_payable --> iia_paid: PAY_BY_DD\n[paymentMethod=\n"DIRECT_DEBIT"]
}
--

== Order Approval

[plantuml,order-approval-state-chart,png]
--
state "OrderApprovalStateTransitionType" as oa {

    state "NEW" as oa_new

    state "APPROVED" as oa_approved
    note right of oa_approved: immutable from this point on

    state "DISCARDED" as oa_discarded
    note right of oa_discarded: associated document\nalso discarded

    [*] -right-> oa_new: INSTANTIATE

    oa_new -down-> oa_approved: COMPLETE_WITH_APPROVAL
    oa_new -right-> oa_discarded : DISCARD

}
--


== Bank Account Verification

[plantuml,bank-account-verification-state-chart,png]
--
state "BankAccountVerificationStateTransitionType" as bbv {

    state "NOT_VERIFIED" as bbv_not_verified
    state "VERIFIED" as bbv_verified

    [*] --right--> bbv_not_verified: \n  INSTANTIATE
    bbv_not_verified -down--> bbv_verified: VERIFY_\nBANK_ACCOUNT

}
--


== Payment Batch Approval

[plantuml,payment-approval-state-chart,png]
--
state "PaymentBatchApprovalStateTransitionType" as pa {

    state "NEW" as pa_new
    state "COMPLETED" as pa_completed

    [*] -right-> pa_new: INSTANTIATE
    pa_new -down-> pa_completed: COMPLETE (as treasurer)

}
--

Notes:

* the incoming invoice state chart is now instantiated via a lifecycle event on invoice (rather than, as previously, listening to the document moving to a 'processed' state)

* ditto bank account's verification state chart

* After bank account verified, respective subscribers update any incoming invoices approved but awaiting verification before moving to `PAID`state
